/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InviteAcceptRouteImport } from './routes/invite.accept'
import { Route as AppWorkspaceSlugRouteImport } from './routes/app.$workspaceSlug'
import { Route as AdminWorkspacesRouteImport } from './routes/admin.workspaces'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AppWorkspaceSlugIndexRouteImport } from './routes/app.$workspaceSlug.index'
import { Route as AppOnboardingCreateWorkspaceRouteImport } from './routes/app.onboarding.create-workspace'
import { Route as AppWorkspaceSlugSettingsRouteImport } from './routes/app.$workspaceSlug.settings'
import { Route as AppWorkspaceSlugScaleRouteImport } from './routes/app.$workspaceSlug.scale'
import { Route as AppWorkspaceSlugInviteRouteImport } from './routes/app.$workspaceSlug.invite'
import { Route as AppWorkspaceSlugDiscoverRouteImport } from './routes/app.$workspaceSlug.discover'
import { Route as AppWorkspaceSlugBuildRouteImport } from './routes/app.$workspaceSlug.build'
import { Route as AppWorkspaceSlugAdminRouteImport } from './routes/app.$workspaceSlug.admin'
import { Route as AppWorkspaceSlugScaleIndexRouteImport } from './routes/app.$workspaceSlug.scale.index'
import { Route as AppWorkspaceSlugDiscoverIndexRouteImport } from './routes/app.$workspaceSlug.discover.index'
import { Route as AppWorkspaceSlugBuildIndexRouteImport } from './routes/app.$workspaceSlug.build.index'
import { Route as AppWorkspaceSlugAssessIndexRouteImport } from './routes/app.$workspaceSlug.assess.index'
import { Route as AppWorkspaceSlugAdminIndexRouteImport } from './routes/app.$workspaceSlug.admin.index'
import { Route as AppWorkspaceSlugScaleRoadmapRouteImport } from './routes/app.$workspaceSlug.scale.roadmap'
import { Route as AppWorkspaceSlugScaleReviewsRouteImport } from './routes/app.$workspaceSlug.scale.reviews'
import { Route as AppWorkspaceSlugScaleGovernanceRouteImport } from './routes/app.$workspaceSlug.scale.governance'
import { Route as AppWorkspaceSlugScaleAuditRouteImport } from './routes/app.$workspaceSlug.scale.audit'
import { Route as AppWorkspaceSlugDiscoverSplatRouteImport } from './routes/app.$workspaceSlug.discover.$'
import { Route as AppWorkspaceSlugBuildTemplatesRouteImport } from './routes/app.$workspaceSlug.build.templates'
import { Route as AppWorkspaceSlugBuildLibraryRouteImport } from './routes/app.$workspaceSlug.build.library'
import { Route as AppWorkspaceSlugBuildApprovalsRouteImport } from './routes/app.$workspaceSlug.build.approvals'
import { Route as AppWorkspaceSlugAssessCompleteRouteImport } from './routes/app.$workspaceSlug.assess.complete'
import { Route as AppWorkspaceSlugAssessAssignmentsRouteImport } from './routes/app.$workspaceSlug.assess.assignments'
import { Route as AppWorkspaceSlugAssessModuleIdRouteImport } from './routes/app.$workspaceSlug.assess.$moduleId'
import { Route as AppWorkspaceSlugAdminSettingsRouteImport } from './routes/app.$workspaceSlug.admin.settings'
import { Route as AppWorkspaceSlugAdminReviewPolicyRouteImport } from './routes/app.$workspaceSlug.admin.review-policy'
import { Route as AppWorkspaceSlugAdminOnboardingRouteImport } from './routes/app.$workspaceSlug.admin.onboarding'
import { Route as AppWorkspaceSlugAdminMembersRouteImport } from './routes/app.$workspaceSlug.admin.members'
import { Route as AppWorkspaceSlugAdminInvoicesRouteImport } from './routes/app.$workspaceSlug.admin.invoices'
import { Route as AppWorkspaceSlugAdminBillingRouteImport } from './routes/app.$workspaceSlug.admin.billing'
import { Route as AppWorkspaceSlugAdminAnalyticsRouteImport } from './routes/app.$workspaceSlug.admin.analytics'
import { Route as AppWorkspaceSlugAssessModuleIdIndexRouteImport } from './routes/app.$workspaceSlug.assess.$moduleId.index'
import { Route as AppWorkspaceSlugScaleUseCaseIdReviewRouteImport } from './routes/app.$workspaceSlug.scale.$useCaseId.review'
import { Route as AppWorkspaceSlugBuildProcessNewRouteImport } from './routes/app.$workspaceSlug.build.process.new'
import { Route as AppWorkspaceSlugBuildProcessIdRouteImport } from './routes/app.$workspaceSlug.build.process.$id'
import { Route as AppWorkspaceSlugAssessModuleIdWorkRouteImport } from './routes/app.$workspaceSlug.assess.$moduleId.work'
import { Route as AppWorkspaceSlugAssessModuleIdStudyRouteImport } from './routes/app.$workspaceSlug.assess.$moduleId.study'
import { Route as AppWorkspaceSlugAssessModuleIdGateRouteImport } from './routes/app.$workspaceSlug.assess.$moduleId.gate'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSlugRoute = AppWorkspaceSlugRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => AppRoute,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/admin/workspaces',
  path: '/admin/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/admin/library',
  path: '/admin/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/admin/catalog',
  path: '/admin/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSlugIndexRoute = AppWorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppOnboardingCreateWorkspaceRoute =
  AppOnboardingCreateWorkspaceRouteImport.update({
    id: '/onboarding/create-workspace',
    path: '/onboarding/create-workspace',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspaceSlugSettingsRoute =
  AppWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugScaleRoute = AppWorkspaceSlugScaleRouteImport.update({
  id: '/scale',
  path: '/scale',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugInviteRoute = AppWorkspaceSlugInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugDiscoverRoute =
  AppWorkspaceSlugDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugBuildRoute = AppWorkspaceSlugBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugAdminRoute = AppWorkspaceSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppWorkspaceSlugRoute,
} as any)
const AppWorkspaceSlugScaleIndexRoute =
  AppWorkspaceSlugScaleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugScaleRoute,
  } as any)
const AppWorkspaceSlugDiscoverIndexRoute =
  AppWorkspaceSlugDiscoverIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugDiscoverRoute,
  } as any)
const AppWorkspaceSlugBuildIndexRoute =
  AppWorkspaceSlugBuildIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugBuildRoute,
  } as any)
const AppWorkspaceSlugAssessIndexRoute =
  AppWorkspaceSlugAssessIndexRouteImport.update({
    id: '/assess/',
    path: '/assess/',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugAdminIndexRoute =
  AppWorkspaceSlugAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugAdminRoute,
  } as any)
const AppWorkspaceSlugScaleRoadmapRoute =
  AppWorkspaceSlugScaleRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => AppWorkspaceSlugScaleRoute,
  } as any)
const AppWorkspaceSlugScaleReviewsRoute =
  AppWorkspaceSlugScaleReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AppWorkspaceSlugScaleRoute,
  } as any)
const AppWorkspaceSlugScaleGovernanceRoute =
  AppWorkspaceSlugScaleGovernanceRouteImport.update({
    id: '/governance',
    path: '/governance',
    getParentRoute: () => AppWorkspaceSlugScaleRoute,
  } as any)
const AppWorkspaceSlugScaleAuditRoute =
  AppWorkspaceSlugScaleAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AppWorkspaceSlugScaleRoute,
  } as any)
const AppWorkspaceSlugDiscoverSplatRoute =
  AppWorkspaceSlugDiscoverSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AppWorkspaceSlugDiscoverRoute,
  } as any)
const AppWorkspaceSlugBuildTemplatesRoute =
  AppWorkspaceSlugBuildTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AppWorkspaceSlugBuildRoute,
  } as any)
const AppWorkspaceSlugBuildLibraryRoute =
  AppWorkspaceSlugBuildLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AppWorkspaceSlugBuildRoute,
  } as any)
const AppWorkspaceSlugBuildApprovalsRoute =
  AppWorkspaceSlugBuildApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AppWorkspaceSlugBuildRoute,
  } as any)
const AppWorkspaceSlugAssessCompleteRoute =
  AppWorkspaceSlugAssessCompleteRouteImport.update({
    id: '/assess/complete',
    path: '/assess/complete',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugAssessAssignmentsRoute =
  AppWorkspaceSlugAssessAssignmentsRouteImport.update({
    id: '/assess/assignments',
    path: '/assess/assignments',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugAssessModuleIdRoute =
  AppWorkspaceSlugAssessModuleIdRouteImport.update({
    id: '/assess/$moduleId',
    path: '/assess/$moduleId',
    getParentRoute: () => AppWorkspaceSlugRoute,
  } as any)
const AppWorkspaceSlugAdminSettingsRoute =
  AppWorkspaceSlugAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceSlugAdminRoute,
  } as any)
const AppWorkspaceSlugAdminReviewPolicyRoute =
  AppWorkspaceSlugAdminReviewPolicyRouteImport.update({
    id: '/review-policy',
    path: '/review-policy',
    getParentRoute: () => AppWorkspaceSlugAdminRoute,
  } as any)
const AppWorkspaceSlugAdminOnboardingRoute =
  AppWorkspaceSlugAdminOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AppWorkspaceSlugAdminRoute,
  } as any)
const AppWorkspaceSlugAdminMembersRoute =
  AppWorkspaceSlugAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppWorkspaceSlugAdminRoute,
  } as any)
const AppWorkspaceSlugAdminInvoicesRoute =
  AppWorkspaceSlugAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AppWorkspaceSlugAdminRoute,
  } as any)
const AppWorkspaceSlugAdminBillingRoute =
  AppWorkspaceSlugAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppWorkspaceSlugAdminRoute,
  } as any)
const AppWorkspaceSlugAdminAnalyticsRoute =
  AppWorkspaceSlugAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppWorkspaceSlugAdminRoute,
  } as any)
const AppWorkspaceSlugAssessModuleIdIndexRoute =
  AppWorkspaceSlugAssessModuleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugAssessModuleIdRoute,
  } as any)
const AppWorkspaceSlugScaleUseCaseIdReviewRoute =
  AppWorkspaceSlugScaleUseCaseIdReviewRouteImport.update({
    id: '/$useCaseId/review',
    path: '/$useCaseId/review',
    getParentRoute: () => AppWorkspaceSlugScaleRoute,
  } as any)
const AppWorkspaceSlugBuildProcessNewRoute =
  AppWorkspaceSlugBuildProcessNewRouteImport.update({
    id: '/process/new',
    path: '/process/new',
    getParentRoute: () => AppWorkspaceSlugBuildRoute,
  } as any)
const AppWorkspaceSlugBuildProcessIdRoute =
  AppWorkspaceSlugBuildProcessIdRouteImport.update({
    id: '/process/$id',
    path: '/process/$id',
    getParentRoute: () => AppWorkspaceSlugBuildRoute,
  } as any)
const AppWorkspaceSlugAssessModuleIdWorkRoute =
  AppWorkspaceSlugAssessModuleIdWorkRouteImport.update({
    id: '/work',
    path: '/work',
    getParentRoute: () => AppWorkspaceSlugAssessModuleIdRoute,
  } as any)
const AppWorkspaceSlugAssessModuleIdStudyRoute =
  AppWorkspaceSlugAssessModuleIdStudyRouteImport.update({
    id: '/study',
    path: '/study',
    getParentRoute: () => AppWorkspaceSlugAssessModuleIdRoute,
  } as any)
const AppWorkspaceSlugAssessModuleIdGateRoute =
  AppWorkspaceSlugAssessModuleIdGateRouteImport.update({
    id: '/gate',
    path: '/gate',
    getParentRoute: () => AppWorkspaceSlugAssessModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/app/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/invite/accept': typeof InviteAcceptRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/$workspaceSlug/admin': typeof AppWorkspaceSlugAdminRouteWithChildren
  '/app/$workspaceSlug/build': typeof AppWorkspaceSlugBuildRouteWithChildren
  '/app/$workspaceSlug/discover': typeof AppWorkspaceSlugDiscoverRouteWithChildren
  '/app/$workspaceSlug/invite': typeof AppWorkspaceSlugInviteRoute
  '/app/$workspaceSlug/scale': typeof AppWorkspaceSlugScaleRouteWithChildren
  '/app/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRoute
  '/app/onboarding/create-workspace': typeof AppOnboardingCreateWorkspaceRoute
  '/app/$workspaceSlug/': typeof AppWorkspaceSlugIndexRoute
  '/app/$workspaceSlug/admin/analytics': typeof AppWorkspaceSlugAdminAnalyticsRoute
  '/app/$workspaceSlug/admin/billing': typeof AppWorkspaceSlugAdminBillingRoute
  '/app/$workspaceSlug/admin/invoices': typeof AppWorkspaceSlugAdminInvoicesRoute
  '/app/$workspaceSlug/admin/members': typeof AppWorkspaceSlugAdminMembersRoute
  '/app/$workspaceSlug/admin/onboarding': typeof AppWorkspaceSlugAdminOnboardingRoute
  '/app/$workspaceSlug/admin/review-policy': typeof AppWorkspaceSlugAdminReviewPolicyRoute
  '/app/$workspaceSlug/admin/settings': typeof AppWorkspaceSlugAdminSettingsRoute
  '/app/$workspaceSlug/assess/$moduleId': typeof AppWorkspaceSlugAssessModuleIdRouteWithChildren
  '/app/$workspaceSlug/assess/assignments': typeof AppWorkspaceSlugAssessAssignmentsRoute
  '/app/$workspaceSlug/assess/complete': typeof AppWorkspaceSlugAssessCompleteRoute
  '/app/$workspaceSlug/build/approvals': typeof AppWorkspaceSlugBuildApprovalsRoute
  '/app/$workspaceSlug/build/library': typeof AppWorkspaceSlugBuildLibraryRoute
  '/app/$workspaceSlug/build/templates': typeof AppWorkspaceSlugBuildTemplatesRoute
  '/app/$workspaceSlug/discover/$': typeof AppWorkspaceSlugDiscoverSplatRoute
  '/app/$workspaceSlug/scale/audit': typeof AppWorkspaceSlugScaleAuditRoute
  '/app/$workspaceSlug/scale/governance': typeof AppWorkspaceSlugScaleGovernanceRoute
  '/app/$workspaceSlug/scale/reviews': typeof AppWorkspaceSlugScaleReviewsRoute
  '/app/$workspaceSlug/scale/roadmap': typeof AppWorkspaceSlugScaleRoadmapRoute
  '/app/$workspaceSlug/admin/': typeof AppWorkspaceSlugAdminIndexRoute
  '/app/$workspaceSlug/assess/': typeof AppWorkspaceSlugAssessIndexRoute
  '/app/$workspaceSlug/build/': typeof AppWorkspaceSlugBuildIndexRoute
  '/app/$workspaceSlug/discover/': typeof AppWorkspaceSlugDiscoverIndexRoute
  '/app/$workspaceSlug/scale/': typeof AppWorkspaceSlugScaleIndexRoute
  '/app/$workspaceSlug/assess/$moduleId/gate': typeof AppWorkspaceSlugAssessModuleIdGateRoute
  '/app/$workspaceSlug/assess/$moduleId/study': typeof AppWorkspaceSlugAssessModuleIdStudyRoute
  '/app/$workspaceSlug/assess/$moduleId/work': typeof AppWorkspaceSlugAssessModuleIdWorkRoute
  '/app/$workspaceSlug/build/process/$id': typeof AppWorkspaceSlugBuildProcessIdRoute
  '/app/$workspaceSlug/build/process/new': typeof AppWorkspaceSlugBuildProcessNewRoute
  '/app/$workspaceSlug/scale/$useCaseId/review': typeof AppWorkspaceSlugScaleUseCaseIdReviewRoute
  '/app/$workspaceSlug/assess/$moduleId/': typeof AppWorkspaceSlugAssessModuleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/$workspaceSlug/invite': typeof AppWorkspaceSlugInviteRoute
  '/app/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRoute
  '/app/onboarding/create-workspace': typeof AppOnboardingCreateWorkspaceRoute
  '/app/$workspaceSlug': typeof AppWorkspaceSlugIndexRoute
  '/app/$workspaceSlug/admin/analytics': typeof AppWorkspaceSlugAdminAnalyticsRoute
  '/app/$workspaceSlug/admin/billing': typeof AppWorkspaceSlugAdminBillingRoute
  '/app/$workspaceSlug/admin/invoices': typeof AppWorkspaceSlugAdminInvoicesRoute
  '/app/$workspaceSlug/admin/members': typeof AppWorkspaceSlugAdminMembersRoute
  '/app/$workspaceSlug/admin/onboarding': typeof AppWorkspaceSlugAdminOnboardingRoute
  '/app/$workspaceSlug/admin/review-policy': typeof AppWorkspaceSlugAdminReviewPolicyRoute
  '/app/$workspaceSlug/admin/settings': typeof AppWorkspaceSlugAdminSettingsRoute
  '/app/$workspaceSlug/assess/assignments': typeof AppWorkspaceSlugAssessAssignmentsRoute
  '/app/$workspaceSlug/assess/complete': typeof AppWorkspaceSlugAssessCompleteRoute
  '/app/$workspaceSlug/build/approvals': typeof AppWorkspaceSlugBuildApprovalsRoute
  '/app/$workspaceSlug/build/library': typeof AppWorkspaceSlugBuildLibraryRoute
  '/app/$workspaceSlug/build/templates': typeof AppWorkspaceSlugBuildTemplatesRoute
  '/app/$workspaceSlug/discover/$': typeof AppWorkspaceSlugDiscoverSplatRoute
  '/app/$workspaceSlug/scale/audit': typeof AppWorkspaceSlugScaleAuditRoute
  '/app/$workspaceSlug/scale/governance': typeof AppWorkspaceSlugScaleGovernanceRoute
  '/app/$workspaceSlug/scale/reviews': typeof AppWorkspaceSlugScaleReviewsRoute
  '/app/$workspaceSlug/scale/roadmap': typeof AppWorkspaceSlugScaleRoadmapRoute
  '/app/$workspaceSlug/admin': typeof AppWorkspaceSlugAdminIndexRoute
  '/app/$workspaceSlug/assess': typeof AppWorkspaceSlugAssessIndexRoute
  '/app/$workspaceSlug/build': typeof AppWorkspaceSlugBuildIndexRoute
  '/app/$workspaceSlug/discover': typeof AppWorkspaceSlugDiscoverIndexRoute
  '/app/$workspaceSlug/scale': typeof AppWorkspaceSlugScaleIndexRoute
  '/app/$workspaceSlug/assess/$moduleId/gate': typeof AppWorkspaceSlugAssessModuleIdGateRoute
  '/app/$workspaceSlug/assess/$moduleId/study': typeof AppWorkspaceSlugAssessModuleIdStudyRoute
  '/app/$workspaceSlug/assess/$moduleId/work': typeof AppWorkspaceSlugAssessModuleIdWorkRoute
  '/app/$workspaceSlug/build/process/$id': typeof AppWorkspaceSlugBuildProcessIdRoute
  '/app/$workspaceSlug/build/process/new': typeof AppWorkspaceSlugBuildProcessNewRoute
  '/app/$workspaceSlug/scale/$useCaseId/review': typeof AppWorkspaceSlugScaleUseCaseIdReviewRoute
  '/app/$workspaceSlug/assess/$moduleId': typeof AppWorkspaceSlugAssessModuleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/app/$workspaceSlug': typeof AppWorkspaceSlugRouteWithChildren
  '/invite/accept': typeof InviteAcceptRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/$workspaceSlug/admin': typeof AppWorkspaceSlugAdminRouteWithChildren
  '/app/$workspaceSlug/build': typeof AppWorkspaceSlugBuildRouteWithChildren
  '/app/$workspaceSlug/discover': typeof AppWorkspaceSlugDiscoverRouteWithChildren
  '/app/$workspaceSlug/invite': typeof AppWorkspaceSlugInviteRoute
  '/app/$workspaceSlug/scale': typeof AppWorkspaceSlugScaleRouteWithChildren
  '/app/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRoute
  '/app/onboarding/create-workspace': typeof AppOnboardingCreateWorkspaceRoute
  '/app/$workspaceSlug/': typeof AppWorkspaceSlugIndexRoute
  '/app/$workspaceSlug/admin/analytics': typeof AppWorkspaceSlugAdminAnalyticsRoute
  '/app/$workspaceSlug/admin/billing': typeof AppWorkspaceSlugAdminBillingRoute
  '/app/$workspaceSlug/admin/invoices': typeof AppWorkspaceSlugAdminInvoicesRoute
  '/app/$workspaceSlug/admin/members': typeof AppWorkspaceSlugAdminMembersRoute
  '/app/$workspaceSlug/admin/onboarding': typeof AppWorkspaceSlugAdminOnboardingRoute
  '/app/$workspaceSlug/admin/review-policy': typeof AppWorkspaceSlugAdminReviewPolicyRoute
  '/app/$workspaceSlug/admin/settings': typeof AppWorkspaceSlugAdminSettingsRoute
  '/app/$workspaceSlug/assess/$moduleId': typeof AppWorkspaceSlugAssessModuleIdRouteWithChildren
  '/app/$workspaceSlug/assess/assignments': typeof AppWorkspaceSlugAssessAssignmentsRoute
  '/app/$workspaceSlug/assess/complete': typeof AppWorkspaceSlugAssessCompleteRoute
  '/app/$workspaceSlug/build/approvals': typeof AppWorkspaceSlugBuildApprovalsRoute
  '/app/$workspaceSlug/build/library': typeof AppWorkspaceSlugBuildLibraryRoute
  '/app/$workspaceSlug/build/templates': typeof AppWorkspaceSlugBuildTemplatesRoute
  '/app/$workspaceSlug/discover/$': typeof AppWorkspaceSlugDiscoverSplatRoute
  '/app/$workspaceSlug/scale/audit': typeof AppWorkspaceSlugScaleAuditRoute
  '/app/$workspaceSlug/scale/governance': typeof AppWorkspaceSlugScaleGovernanceRoute
  '/app/$workspaceSlug/scale/reviews': typeof AppWorkspaceSlugScaleReviewsRoute
  '/app/$workspaceSlug/scale/roadmap': typeof AppWorkspaceSlugScaleRoadmapRoute
  '/app/$workspaceSlug/admin/': typeof AppWorkspaceSlugAdminIndexRoute
  '/app/$workspaceSlug/assess/': typeof AppWorkspaceSlugAssessIndexRoute
  '/app/$workspaceSlug/build/': typeof AppWorkspaceSlugBuildIndexRoute
  '/app/$workspaceSlug/discover/': typeof AppWorkspaceSlugDiscoverIndexRoute
  '/app/$workspaceSlug/scale/': typeof AppWorkspaceSlugScaleIndexRoute
  '/app/$workspaceSlug/assess/$moduleId/gate': typeof AppWorkspaceSlugAssessModuleIdGateRoute
  '/app/$workspaceSlug/assess/$moduleId/study': typeof AppWorkspaceSlugAssessModuleIdStudyRoute
  '/app/$workspaceSlug/assess/$moduleId/work': typeof AppWorkspaceSlugAssessModuleIdWorkRoute
  '/app/$workspaceSlug/build/process/$id': typeof AppWorkspaceSlugBuildProcessIdRoute
  '/app/$workspaceSlug/build/process/new': typeof AppWorkspaceSlugBuildProcessNewRoute
  '/app/$workspaceSlug/scale/$useCaseId/review': typeof AppWorkspaceSlugScaleUseCaseIdReviewRoute
  '/app/$workspaceSlug/assess/$moduleId/': typeof AppWorkspaceSlugAssessModuleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/catalog'
    | '/admin/content'
    | '/admin/library'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/workspaces'
    | '/app/$workspaceSlug'
    | '/invite/accept'
    | '/admin/'
    | '/app/'
    | '/app/$workspaceSlug/admin'
    | '/app/$workspaceSlug/build'
    | '/app/$workspaceSlug/discover'
    | '/app/$workspaceSlug/invite'
    | '/app/$workspaceSlug/scale'
    | '/app/$workspaceSlug/settings'
    | '/app/onboarding/create-workspace'
    | '/app/$workspaceSlug/'
    | '/app/$workspaceSlug/admin/analytics'
    | '/app/$workspaceSlug/admin/billing'
    | '/app/$workspaceSlug/admin/invoices'
    | '/app/$workspaceSlug/admin/members'
    | '/app/$workspaceSlug/admin/onboarding'
    | '/app/$workspaceSlug/admin/review-policy'
    | '/app/$workspaceSlug/admin/settings'
    | '/app/$workspaceSlug/assess/$moduleId'
    | '/app/$workspaceSlug/assess/assignments'
    | '/app/$workspaceSlug/assess/complete'
    | '/app/$workspaceSlug/build/approvals'
    | '/app/$workspaceSlug/build/library'
    | '/app/$workspaceSlug/build/templates'
    | '/app/$workspaceSlug/discover/$'
    | '/app/$workspaceSlug/scale/audit'
    | '/app/$workspaceSlug/scale/governance'
    | '/app/$workspaceSlug/scale/reviews'
    | '/app/$workspaceSlug/scale/roadmap'
    | '/app/$workspaceSlug/admin/'
    | '/app/$workspaceSlug/assess/'
    | '/app/$workspaceSlug/build/'
    | '/app/$workspaceSlug/discover/'
    | '/app/$workspaceSlug/scale/'
    | '/app/$workspaceSlug/assess/$moduleId/gate'
    | '/app/$workspaceSlug/assess/$moduleId/study'
    | '/app/$workspaceSlug/assess/$moduleId/work'
    | '/app/$workspaceSlug/build/process/$id'
    | '/app/$workspaceSlug/build/process/new'
    | '/app/$workspaceSlug/scale/$useCaseId/review'
    | '/app/$workspaceSlug/assess/$moduleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/catalog'
    | '/admin/content'
    | '/admin/library'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/workspaces'
    | '/invite/accept'
    | '/admin'
    | '/app'
    | '/app/$workspaceSlug/invite'
    | '/app/$workspaceSlug/settings'
    | '/app/onboarding/create-workspace'
    | '/app/$workspaceSlug'
    | '/app/$workspaceSlug/admin/analytics'
    | '/app/$workspaceSlug/admin/billing'
    | '/app/$workspaceSlug/admin/invoices'
    | '/app/$workspaceSlug/admin/members'
    | '/app/$workspaceSlug/admin/onboarding'
    | '/app/$workspaceSlug/admin/review-policy'
    | '/app/$workspaceSlug/admin/settings'
    | '/app/$workspaceSlug/assess/assignments'
    | '/app/$workspaceSlug/assess/complete'
    | '/app/$workspaceSlug/build/approvals'
    | '/app/$workspaceSlug/build/library'
    | '/app/$workspaceSlug/build/templates'
    | '/app/$workspaceSlug/discover/$'
    | '/app/$workspaceSlug/scale/audit'
    | '/app/$workspaceSlug/scale/governance'
    | '/app/$workspaceSlug/scale/reviews'
    | '/app/$workspaceSlug/scale/roadmap'
    | '/app/$workspaceSlug/admin'
    | '/app/$workspaceSlug/assess'
    | '/app/$workspaceSlug/build'
    | '/app/$workspaceSlug/discover'
    | '/app/$workspaceSlug/scale'
    | '/app/$workspaceSlug/assess/$moduleId/gate'
    | '/app/$workspaceSlug/assess/$moduleId/study'
    | '/app/$workspaceSlug/assess/$moduleId/work'
    | '/app/$workspaceSlug/build/process/$id'
    | '/app/$workspaceSlug/build/process/new'
    | '/app/$workspaceSlug/scale/$useCaseId/review'
    | '/app/$workspaceSlug/assess/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/catalog'
    | '/admin/content'
    | '/admin/library'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/workspaces'
    | '/app/$workspaceSlug'
    | '/invite/accept'
    | '/admin/'
    | '/app/'
    | '/app/$workspaceSlug/admin'
    | '/app/$workspaceSlug/build'
    | '/app/$workspaceSlug/discover'
    | '/app/$workspaceSlug/invite'
    | '/app/$workspaceSlug/scale'
    | '/app/$workspaceSlug/settings'
    | '/app/onboarding/create-workspace'
    | '/app/$workspaceSlug/'
    | '/app/$workspaceSlug/admin/analytics'
    | '/app/$workspaceSlug/admin/billing'
    | '/app/$workspaceSlug/admin/invoices'
    | '/app/$workspaceSlug/admin/members'
    | '/app/$workspaceSlug/admin/onboarding'
    | '/app/$workspaceSlug/admin/review-policy'
    | '/app/$workspaceSlug/admin/settings'
    | '/app/$workspaceSlug/assess/$moduleId'
    | '/app/$workspaceSlug/assess/assignments'
    | '/app/$workspaceSlug/assess/complete'
    | '/app/$workspaceSlug/build/approvals'
    | '/app/$workspaceSlug/build/library'
    | '/app/$workspaceSlug/build/templates'
    | '/app/$workspaceSlug/discover/$'
    | '/app/$workspaceSlug/scale/audit'
    | '/app/$workspaceSlug/scale/governance'
    | '/app/$workspaceSlug/scale/reviews'
    | '/app/$workspaceSlug/scale/roadmap'
    | '/app/$workspaceSlug/admin/'
    | '/app/$workspaceSlug/assess/'
    | '/app/$workspaceSlug/build/'
    | '/app/$workspaceSlug/discover/'
    | '/app/$workspaceSlug/scale/'
    | '/app/$workspaceSlug/assess/$moduleId/gate'
    | '/app/$workspaceSlug/assess/$moduleId/study'
    | '/app/$workspaceSlug/assess/$moduleId/work'
    | '/app/$workspaceSlug/build/process/$id'
    | '/app/$workspaceSlug/build/process/new'
    | '/app/$workspaceSlug/scale/$useCaseId/review'
    | '/app/$workspaceSlug/assess/$moduleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$workspaceSlug': {
      id: '/app/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/app/$workspaceSlug'
      preLoaderRoute: typeof AppWorkspaceSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/workspaces': {
      id: '/admin/workspaces'
      path: '/admin/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/admin/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$workspaceSlug/': {
      id: '/app/$workspaceSlug/'
      path: '/'
      fullPath: '/app/$workspaceSlug/'
      preLoaderRoute: typeof AppWorkspaceSlugIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/onboarding/create-workspace': {
      id: '/app/onboarding/create-workspace'
      path: '/onboarding/create-workspace'
      fullPath: '/app/onboarding/create-workspace'
      preLoaderRoute: typeof AppOnboardingCreateWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$workspaceSlug/settings': {
      id: '/app/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/app/$workspaceSlug/settings'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/scale': {
      id: '/app/$workspaceSlug/scale'
      path: '/scale'
      fullPath: '/app/$workspaceSlug/scale'
      preLoaderRoute: typeof AppWorkspaceSlugScaleRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/invite': {
      id: '/app/$workspaceSlug/invite'
      path: '/invite'
      fullPath: '/app/$workspaceSlug/invite'
      preLoaderRoute: typeof AppWorkspaceSlugInviteRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/discover': {
      id: '/app/$workspaceSlug/discover'
      path: '/discover'
      fullPath: '/app/$workspaceSlug/discover'
      preLoaderRoute: typeof AppWorkspaceSlugDiscoverRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/build': {
      id: '/app/$workspaceSlug/build'
      path: '/build'
      fullPath: '/app/$workspaceSlug/build'
      preLoaderRoute: typeof AppWorkspaceSlugBuildRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/admin': {
      id: '/app/$workspaceSlug/admin'
      path: '/admin'
      fullPath: '/app/$workspaceSlug/admin'
      preLoaderRoute: typeof AppWorkspaceSlugAdminRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/scale/': {
      id: '/app/$workspaceSlug/scale/'
      path: '/'
      fullPath: '/app/$workspaceSlug/scale/'
      preLoaderRoute: typeof AppWorkspaceSlugScaleIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugScaleRoute
    }
    '/app/$workspaceSlug/discover/': {
      id: '/app/$workspaceSlug/discover/'
      path: '/'
      fullPath: '/app/$workspaceSlug/discover/'
      preLoaderRoute: typeof AppWorkspaceSlugDiscoverIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugDiscoverRoute
    }
    '/app/$workspaceSlug/build/': {
      id: '/app/$workspaceSlug/build/'
      path: '/'
      fullPath: '/app/$workspaceSlug/build/'
      preLoaderRoute: typeof AppWorkspaceSlugBuildIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugBuildRoute
    }
    '/app/$workspaceSlug/assess/': {
      id: '/app/$workspaceSlug/assess/'
      path: '/assess'
      fullPath: '/app/$workspaceSlug/assess/'
      preLoaderRoute: typeof AppWorkspaceSlugAssessIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/admin/': {
      id: '/app/$workspaceSlug/admin/'
      path: '/'
      fullPath: '/app/$workspaceSlug/admin/'
      preLoaderRoute: typeof AppWorkspaceSlugAdminIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRoute
    }
    '/app/$workspaceSlug/scale/roadmap': {
      id: '/app/$workspaceSlug/scale/roadmap'
      path: '/roadmap'
      fullPath: '/app/$workspaceSlug/scale/roadmap'
      preLoaderRoute: typeof AppWorkspaceSlugScaleRoadmapRouteImport
      parentRoute: typeof AppWorkspaceSlugScaleRoute
    }
    '/app/$workspaceSlug/scale/reviews': {
      id: '/app/$workspaceSlug/scale/reviews'
      path: '/reviews'
      fullPath: '/app/$workspaceSlug/scale/reviews'
      preLoaderRoute: typeof AppWorkspaceSlugScaleReviewsRouteImport
      parentRoute: typeof AppWorkspaceSlugScaleRoute
    }
    '/app/$workspaceSlug/scale/governance': {
      id: '/app/$workspaceSlug/scale/governance'
      path: '/governance'
      fullPath: '/app/$workspaceSlug/scale/governance'
      preLoaderRoute: typeof AppWorkspaceSlugScaleGovernanceRouteImport
      parentRoute: typeof AppWorkspaceSlugScaleRoute
    }
    '/app/$workspaceSlug/scale/audit': {
      id: '/app/$workspaceSlug/scale/audit'
      path: '/audit'
      fullPath: '/app/$workspaceSlug/scale/audit'
      preLoaderRoute: typeof AppWorkspaceSlugScaleAuditRouteImport
      parentRoute: typeof AppWorkspaceSlugScaleRoute
    }
    '/app/$workspaceSlug/discover/$': {
      id: '/app/$workspaceSlug/discover/$'
      path: '/$'
      fullPath: '/app/$workspaceSlug/discover/$'
      preLoaderRoute: typeof AppWorkspaceSlugDiscoverSplatRouteImport
      parentRoute: typeof AppWorkspaceSlugDiscoverRoute
    }
    '/app/$workspaceSlug/build/templates': {
      id: '/app/$workspaceSlug/build/templates'
      path: '/templates'
      fullPath: '/app/$workspaceSlug/build/templates'
      preLoaderRoute: typeof AppWorkspaceSlugBuildTemplatesRouteImport
      parentRoute: typeof AppWorkspaceSlugBuildRoute
    }
    '/app/$workspaceSlug/build/library': {
      id: '/app/$workspaceSlug/build/library'
      path: '/library'
      fullPath: '/app/$workspaceSlug/build/library'
      preLoaderRoute: typeof AppWorkspaceSlugBuildLibraryRouteImport
      parentRoute: typeof AppWorkspaceSlugBuildRoute
    }
    '/app/$workspaceSlug/build/approvals': {
      id: '/app/$workspaceSlug/build/approvals'
      path: '/approvals'
      fullPath: '/app/$workspaceSlug/build/approvals'
      preLoaderRoute: typeof AppWorkspaceSlugBuildApprovalsRouteImport
      parentRoute: typeof AppWorkspaceSlugBuildRoute
    }
    '/app/$workspaceSlug/assess/complete': {
      id: '/app/$workspaceSlug/assess/complete'
      path: '/assess/complete'
      fullPath: '/app/$workspaceSlug/assess/complete'
      preLoaderRoute: typeof AppWorkspaceSlugAssessCompleteRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/assess/assignments': {
      id: '/app/$workspaceSlug/assess/assignments'
      path: '/assess/assignments'
      fullPath: '/app/$workspaceSlug/assess/assignments'
      preLoaderRoute: typeof AppWorkspaceSlugAssessAssignmentsRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/assess/$moduleId': {
      id: '/app/$workspaceSlug/assess/$moduleId'
      path: '/assess/$moduleId'
      fullPath: '/app/$workspaceSlug/assess/$moduleId'
      preLoaderRoute: typeof AppWorkspaceSlugAssessModuleIdRouteImport
      parentRoute: typeof AppWorkspaceSlugRoute
    }
    '/app/$workspaceSlug/admin/settings': {
      id: '/app/$workspaceSlug/admin/settings'
      path: '/settings'
      fullPath: '/app/$workspaceSlug/admin/settings'
      preLoaderRoute: typeof AppWorkspaceSlugAdminSettingsRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRoute
    }
    '/app/$workspaceSlug/admin/review-policy': {
      id: '/app/$workspaceSlug/admin/review-policy'
      path: '/review-policy'
      fullPath: '/app/$workspaceSlug/admin/review-policy'
      preLoaderRoute: typeof AppWorkspaceSlugAdminReviewPolicyRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRoute
    }
    '/app/$workspaceSlug/admin/onboarding': {
      id: '/app/$workspaceSlug/admin/onboarding'
      path: '/onboarding'
      fullPath: '/app/$workspaceSlug/admin/onboarding'
      preLoaderRoute: typeof AppWorkspaceSlugAdminOnboardingRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRoute
    }
    '/app/$workspaceSlug/admin/members': {
      id: '/app/$workspaceSlug/admin/members'
      path: '/members'
      fullPath: '/app/$workspaceSlug/admin/members'
      preLoaderRoute: typeof AppWorkspaceSlugAdminMembersRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRoute
    }
    '/app/$workspaceSlug/admin/invoices': {
      id: '/app/$workspaceSlug/admin/invoices'
      path: '/invoices'
      fullPath: '/app/$workspaceSlug/admin/invoices'
      preLoaderRoute: typeof AppWorkspaceSlugAdminInvoicesRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRoute
    }
    '/app/$workspaceSlug/admin/billing': {
      id: '/app/$workspaceSlug/admin/billing'
      path: '/billing'
      fullPath: '/app/$workspaceSlug/admin/billing'
      preLoaderRoute: typeof AppWorkspaceSlugAdminBillingRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRoute
    }
    '/app/$workspaceSlug/admin/analytics': {
      id: '/app/$workspaceSlug/admin/analytics'
      path: '/analytics'
      fullPath: '/app/$workspaceSlug/admin/analytics'
      preLoaderRoute: typeof AppWorkspaceSlugAdminAnalyticsRouteImport
      parentRoute: typeof AppWorkspaceSlugAdminRoute
    }
    '/app/$workspaceSlug/assess/$moduleId/': {
      id: '/app/$workspaceSlug/assess/$moduleId/'
      path: '/'
      fullPath: '/app/$workspaceSlug/assess/$moduleId/'
      preLoaderRoute: typeof AppWorkspaceSlugAssessModuleIdIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugAssessModuleIdRoute
    }
    '/app/$workspaceSlug/scale/$useCaseId/review': {
      id: '/app/$workspaceSlug/scale/$useCaseId/review'
      path: '/$useCaseId/review'
      fullPath: '/app/$workspaceSlug/scale/$useCaseId/review'
      preLoaderRoute: typeof AppWorkspaceSlugScaleUseCaseIdReviewRouteImport
      parentRoute: typeof AppWorkspaceSlugScaleRoute
    }
    '/app/$workspaceSlug/build/process/new': {
      id: '/app/$workspaceSlug/build/process/new'
      path: '/process/new'
      fullPath: '/app/$workspaceSlug/build/process/new'
      preLoaderRoute: typeof AppWorkspaceSlugBuildProcessNewRouteImport
      parentRoute: typeof AppWorkspaceSlugBuildRoute
    }
    '/app/$workspaceSlug/build/process/$id': {
      id: '/app/$workspaceSlug/build/process/$id'
      path: '/process/$id'
      fullPath: '/app/$workspaceSlug/build/process/$id'
      preLoaderRoute: typeof AppWorkspaceSlugBuildProcessIdRouteImport
      parentRoute: typeof AppWorkspaceSlugBuildRoute
    }
    '/app/$workspaceSlug/assess/$moduleId/work': {
      id: '/app/$workspaceSlug/assess/$moduleId/work'
      path: '/work'
      fullPath: '/app/$workspaceSlug/assess/$moduleId/work'
      preLoaderRoute: typeof AppWorkspaceSlugAssessModuleIdWorkRouteImport
      parentRoute: typeof AppWorkspaceSlugAssessModuleIdRoute
    }
    '/app/$workspaceSlug/assess/$moduleId/study': {
      id: '/app/$workspaceSlug/assess/$moduleId/study'
      path: '/study'
      fullPath: '/app/$workspaceSlug/assess/$moduleId/study'
      preLoaderRoute: typeof AppWorkspaceSlugAssessModuleIdStudyRouteImport
      parentRoute: typeof AppWorkspaceSlugAssessModuleIdRoute
    }
    '/app/$workspaceSlug/assess/$moduleId/gate': {
      id: '/app/$workspaceSlug/assess/$moduleId/gate'
      path: '/gate'
      fullPath: '/app/$workspaceSlug/assess/$moduleId/gate'
      preLoaderRoute: typeof AppWorkspaceSlugAssessModuleIdGateRouteImport
      parentRoute: typeof AppWorkspaceSlugAssessModuleIdRoute
    }
  }
}

interface AppWorkspaceSlugAdminRouteChildren {
  AppWorkspaceSlugAdminAnalyticsRoute: typeof AppWorkspaceSlugAdminAnalyticsRoute
  AppWorkspaceSlugAdminBillingRoute: typeof AppWorkspaceSlugAdminBillingRoute
  AppWorkspaceSlugAdminInvoicesRoute: typeof AppWorkspaceSlugAdminInvoicesRoute
  AppWorkspaceSlugAdminMembersRoute: typeof AppWorkspaceSlugAdminMembersRoute
  AppWorkspaceSlugAdminOnboardingRoute: typeof AppWorkspaceSlugAdminOnboardingRoute
  AppWorkspaceSlugAdminReviewPolicyRoute: typeof AppWorkspaceSlugAdminReviewPolicyRoute
  AppWorkspaceSlugAdminSettingsRoute: typeof AppWorkspaceSlugAdminSettingsRoute
  AppWorkspaceSlugAdminIndexRoute: typeof AppWorkspaceSlugAdminIndexRoute
}

const AppWorkspaceSlugAdminRouteChildren: AppWorkspaceSlugAdminRouteChildren = {
  AppWorkspaceSlugAdminAnalyticsRoute: AppWorkspaceSlugAdminAnalyticsRoute,
  AppWorkspaceSlugAdminBillingRoute: AppWorkspaceSlugAdminBillingRoute,
  AppWorkspaceSlugAdminInvoicesRoute: AppWorkspaceSlugAdminInvoicesRoute,
  AppWorkspaceSlugAdminMembersRoute: AppWorkspaceSlugAdminMembersRoute,
  AppWorkspaceSlugAdminOnboardingRoute: AppWorkspaceSlugAdminOnboardingRoute,
  AppWorkspaceSlugAdminReviewPolicyRoute:
    AppWorkspaceSlugAdminReviewPolicyRoute,
  AppWorkspaceSlugAdminSettingsRoute: AppWorkspaceSlugAdminSettingsRoute,
  AppWorkspaceSlugAdminIndexRoute: AppWorkspaceSlugAdminIndexRoute,
}

const AppWorkspaceSlugAdminRouteWithChildren =
  AppWorkspaceSlugAdminRoute._addFileChildren(
    AppWorkspaceSlugAdminRouteChildren,
  )

interface AppWorkspaceSlugBuildRouteChildren {
  AppWorkspaceSlugBuildApprovalsRoute: typeof AppWorkspaceSlugBuildApprovalsRoute
  AppWorkspaceSlugBuildLibraryRoute: typeof AppWorkspaceSlugBuildLibraryRoute
  AppWorkspaceSlugBuildTemplatesRoute: typeof AppWorkspaceSlugBuildTemplatesRoute
  AppWorkspaceSlugBuildIndexRoute: typeof AppWorkspaceSlugBuildIndexRoute
  AppWorkspaceSlugBuildProcessIdRoute: typeof AppWorkspaceSlugBuildProcessIdRoute
  AppWorkspaceSlugBuildProcessNewRoute: typeof AppWorkspaceSlugBuildProcessNewRoute
}

const AppWorkspaceSlugBuildRouteChildren: AppWorkspaceSlugBuildRouteChildren = {
  AppWorkspaceSlugBuildApprovalsRoute: AppWorkspaceSlugBuildApprovalsRoute,
  AppWorkspaceSlugBuildLibraryRoute: AppWorkspaceSlugBuildLibraryRoute,
  AppWorkspaceSlugBuildTemplatesRoute: AppWorkspaceSlugBuildTemplatesRoute,
  AppWorkspaceSlugBuildIndexRoute: AppWorkspaceSlugBuildIndexRoute,
  AppWorkspaceSlugBuildProcessIdRoute: AppWorkspaceSlugBuildProcessIdRoute,
  AppWorkspaceSlugBuildProcessNewRoute: AppWorkspaceSlugBuildProcessNewRoute,
}

const AppWorkspaceSlugBuildRouteWithChildren =
  AppWorkspaceSlugBuildRoute._addFileChildren(
    AppWorkspaceSlugBuildRouteChildren,
  )

interface AppWorkspaceSlugDiscoverRouteChildren {
  AppWorkspaceSlugDiscoverSplatRoute: typeof AppWorkspaceSlugDiscoverSplatRoute
  AppWorkspaceSlugDiscoverIndexRoute: typeof AppWorkspaceSlugDiscoverIndexRoute
}

const AppWorkspaceSlugDiscoverRouteChildren: AppWorkspaceSlugDiscoverRouteChildren =
  {
    AppWorkspaceSlugDiscoverSplatRoute: AppWorkspaceSlugDiscoverSplatRoute,
    AppWorkspaceSlugDiscoverIndexRoute: AppWorkspaceSlugDiscoverIndexRoute,
  }

const AppWorkspaceSlugDiscoverRouteWithChildren =
  AppWorkspaceSlugDiscoverRoute._addFileChildren(
    AppWorkspaceSlugDiscoverRouteChildren,
  )

interface AppWorkspaceSlugScaleRouteChildren {
  AppWorkspaceSlugScaleAuditRoute: typeof AppWorkspaceSlugScaleAuditRoute
  AppWorkspaceSlugScaleGovernanceRoute: typeof AppWorkspaceSlugScaleGovernanceRoute
  AppWorkspaceSlugScaleReviewsRoute: typeof AppWorkspaceSlugScaleReviewsRoute
  AppWorkspaceSlugScaleRoadmapRoute: typeof AppWorkspaceSlugScaleRoadmapRoute
  AppWorkspaceSlugScaleIndexRoute: typeof AppWorkspaceSlugScaleIndexRoute
  AppWorkspaceSlugScaleUseCaseIdReviewRoute: typeof AppWorkspaceSlugScaleUseCaseIdReviewRoute
}

const AppWorkspaceSlugScaleRouteChildren: AppWorkspaceSlugScaleRouteChildren = {
  AppWorkspaceSlugScaleAuditRoute: AppWorkspaceSlugScaleAuditRoute,
  AppWorkspaceSlugScaleGovernanceRoute: AppWorkspaceSlugScaleGovernanceRoute,
  AppWorkspaceSlugScaleReviewsRoute: AppWorkspaceSlugScaleReviewsRoute,
  AppWorkspaceSlugScaleRoadmapRoute: AppWorkspaceSlugScaleRoadmapRoute,
  AppWorkspaceSlugScaleIndexRoute: AppWorkspaceSlugScaleIndexRoute,
  AppWorkspaceSlugScaleUseCaseIdReviewRoute:
    AppWorkspaceSlugScaleUseCaseIdReviewRoute,
}

const AppWorkspaceSlugScaleRouteWithChildren =
  AppWorkspaceSlugScaleRoute._addFileChildren(
    AppWorkspaceSlugScaleRouteChildren,
  )

interface AppWorkspaceSlugAssessModuleIdRouteChildren {
  AppWorkspaceSlugAssessModuleIdGateRoute: typeof AppWorkspaceSlugAssessModuleIdGateRoute
  AppWorkspaceSlugAssessModuleIdStudyRoute: typeof AppWorkspaceSlugAssessModuleIdStudyRoute
  AppWorkspaceSlugAssessModuleIdWorkRoute: typeof AppWorkspaceSlugAssessModuleIdWorkRoute
  AppWorkspaceSlugAssessModuleIdIndexRoute: typeof AppWorkspaceSlugAssessModuleIdIndexRoute
}

const AppWorkspaceSlugAssessModuleIdRouteChildren: AppWorkspaceSlugAssessModuleIdRouteChildren =
  {
    AppWorkspaceSlugAssessModuleIdGateRoute:
      AppWorkspaceSlugAssessModuleIdGateRoute,
    AppWorkspaceSlugAssessModuleIdStudyRoute:
      AppWorkspaceSlugAssessModuleIdStudyRoute,
    AppWorkspaceSlugAssessModuleIdWorkRoute:
      AppWorkspaceSlugAssessModuleIdWorkRoute,
    AppWorkspaceSlugAssessModuleIdIndexRoute:
      AppWorkspaceSlugAssessModuleIdIndexRoute,
  }

const AppWorkspaceSlugAssessModuleIdRouteWithChildren =
  AppWorkspaceSlugAssessModuleIdRoute._addFileChildren(
    AppWorkspaceSlugAssessModuleIdRouteChildren,
  )

interface AppWorkspaceSlugRouteChildren {
  AppWorkspaceSlugAdminRoute: typeof AppWorkspaceSlugAdminRouteWithChildren
  AppWorkspaceSlugBuildRoute: typeof AppWorkspaceSlugBuildRouteWithChildren
  AppWorkspaceSlugDiscoverRoute: typeof AppWorkspaceSlugDiscoverRouteWithChildren
  AppWorkspaceSlugInviteRoute: typeof AppWorkspaceSlugInviteRoute
  AppWorkspaceSlugScaleRoute: typeof AppWorkspaceSlugScaleRouteWithChildren
  AppWorkspaceSlugSettingsRoute: typeof AppWorkspaceSlugSettingsRoute
  AppWorkspaceSlugIndexRoute: typeof AppWorkspaceSlugIndexRoute
  AppWorkspaceSlugAssessModuleIdRoute: typeof AppWorkspaceSlugAssessModuleIdRouteWithChildren
  AppWorkspaceSlugAssessAssignmentsRoute: typeof AppWorkspaceSlugAssessAssignmentsRoute
  AppWorkspaceSlugAssessCompleteRoute: typeof AppWorkspaceSlugAssessCompleteRoute
  AppWorkspaceSlugAssessIndexRoute: typeof AppWorkspaceSlugAssessIndexRoute
}

const AppWorkspaceSlugRouteChildren: AppWorkspaceSlugRouteChildren = {
  AppWorkspaceSlugAdminRoute: AppWorkspaceSlugAdminRouteWithChildren,
  AppWorkspaceSlugBuildRoute: AppWorkspaceSlugBuildRouteWithChildren,
  AppWorkspaceSlugDiscoverRoute: AppWorkspaceSlugDiscoverRouteWithChildren,
  AppWorkspaceSlugInviteRoute: AppWorkspaceSlugInviteRoute,
  AppWorkspaceSlugScaleRoute: AppWorkspaceSlugScaleRouteWithChildren,
  AppWorkspaceSlugSettingsRoute: AppWorkspaceSlugSettingsRoute,
  AppWorkspaceSlugIndexRoute: AppWorkspaceSlugIndexRoute,
  AppWorkspaceSlugAssessModuleIdRoute:
    AppWorkspaceSlugAssessModuleIdRouteWithChildren,
  AppWorkspaceSlugAssessAssignmentsRoute:
    AppWorkspaceSlugAssessAssignmentsRoute,
  AppWorkspaceSlugAssessCompleteRoute: AppWorkspaceSlugAssessCompleteRoute,
  AppWorkspaceSlugAssessIndexRoute: AppWorkspaceSlugAssessIndexRoute,
}

const AppWorkspaceSlugRouteWithChildren =
  AppWorkspaceSlugRoute._addFileChildren(AppWorkspaceSlugRouteChildren)

interface AppRouteChildren {
  AppWorkspaceSlugRoute: typeof AppWorkspaceSlugRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppOnboardingCreateWorkspaceRoute: typeof AppOnboardingCreateWorkspaceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkspaceSlugRoute: AppWorkspaceSlugRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppOnboardingCreateWorkspaceRoute: AppOnboardingCreateWorkspaceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminContentRoute: AdminContentRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkspacesRoute: AdminWorkspacesRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
