
-- Seed starter Discover library content (idempotent via stable UUIDs)
INSERT INTO public.library_items
  (id, workspace_id, type, title, summary, module_ids, phase_ids, tags, published, content_url, metadata, version)
VALUES
  ('11111111-0000-4000-8000-000000000001', NULL, 'prompts',
   'Six-Element Prompt for Invoice Review',
   'A beginner-friendly prompt template for asking an AI assistant to review invoice data with clear role, task, context, constraints, examples, and output format.',
   ARRAY['m03']::text[], ARRAY['discover','assess']::text[],
   ARRAY['prompting','invoice-ocr','six-element','beginner']::text[],
   true, NULL,
   '{"prompt_text":"Role: You are an invoice operations assistant. Task: Review the invoice fields below and identify missing, suspicious, or inconsistent values. Context: The invoice may come from OCR and may contain errors. Constraints: Do not approve payment. Do not invent missing values. Flag uncertainty. Example checks: supplier name, invoice number, VAT/tax, total amount, due date, line-item consistency. Output: Return a JSON object with status, issues, confidence, and recommended human review action.","framework":"six-element","tested_on":["ChatGPT","Claude","Gemini"],"expected_input":"OCR text or structured invoice fields","expected_output":"JSON review result with issues and confidence","difficulty":"beginner"}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000002', NULL, 'agents',
   'Invoice Exception Routing Agent',
   'A starter architecture for an agent that routes invoice exceptions to the right human reviewer before any payment action.',
   ARRAY['m06','m09','m11']::text[], ARRAY['build','scale']::text[],
   ARRAY['agents','human-in-the-loop','invoice-ocr','exceptions']::text[],
   true, NULL,
   '{"architecture_spec":"Trigger: new extracted invoice. Steps: validate fields, classify exception type, check payment risk, route to reviewer, log decision, prepare export only after approval.","n8n_template_url":"","screenshots":[],"platform":"n8n / Make / custom workflow","mcp_integrations":["storage","notification","audit-log"]}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000003', NULL, 'assistants',
   'Finance Policy Q&A Assistant',
   'An assistant concept for answering questions from finance policies without making payment decisions.',
   ARRAY['m04']::text[], ARRAY['build']::text[],
   ARRAY['assistants','knowledge-base','finance','rag']::text[],
   true, NULL,
   '{"description":"A retrieval-based assistant that answers finance policy questions and cites the source policy section.","setup_instructions":"Upload approved finance policies, define refusal rules, test against known policy questions, and restrict the assistant from approving payments.","recommended_platform":"ChatGPT custom GPT / Claude Project / internal RAG app","knowledge_base_type":"policy documents and SOPs"}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000004', NULL, 'tools',
   'OCR Tool Evaluation Checklist',
   'A lightweight tool card for comparing OCR providers on extraction quality, governance, and auditability.',
   ARRAY['m07','m08']::text[], ARRAY['assess','build']::text[],
   ARRAY['tools','ocr','governance','vendor-selection']::text[],
   true, NULL,
   '{"provider":"Generic OCR provider","capability":"Invoice OCR and document extraction","governance_posture":{"data_residency":"Check vendor region options","training_optout":"Required for sensitive finance data","mcp_support":"Optional","audit_logs":"Required for production workflows"},"pricing_tier":"usage-based","url":""}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000005', NULL, 'videos',
   'What Tokens Mean for AI Cost',
   'A short starter lesson explaining how tokens affect AI context size and operating cost.',
   ARRAY['m01']::text[], ARRAY['discover']::text[],
   ARRAY['tokens','cost','ai-basics','beginner']::text[],
   true, NULL,
   '{"video_url":"","duration_seconds":300,"transcript_url":"","chapter_markers":[{"time":0,"label":"What is a token?"},{"time":90,"label":"Why context length matters"},{"time":180,"label":"How cost scales"}],"thumbnail_url":""}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000006', NULL, 'presentations',
   'AI Builder Orientation Deck',
   'A starter deck outline for introducing the Discover, Assess, Build, and Scale journey.',
   ARRAY['m01']::text[], ARRAY['discover']::text[],
   ARRAY['orientation','deck','program-overview']::text[],
   true, NULL,
   '{"file_url":"","slide_count":12,"format":"pptx"}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000007', NULL, 'documents',
   'AI Use Case Intake Template',
   'A starter document for capturing a use case, users, data sources, risks, and expected outcomes.',
   ARRAY['m01','m02']::text[], ARRAY['discover','assess']::text[],
   ARRAY['template','use-case','intake','scope']::text[],
   true, NULL,
   '{"file_url":"","document_type":"template","page_count":3}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000008', NULL, 'case_studies',
   'Finance Team Reduces Invoice Review Backlog',
   'A sample case study showing how an AI workflow can reduce manual invoice triage while keeping human approval.',
   ARRAY['m01','m06','m09']::text[], ARRAY['discover','assess']::text[],
   ARRAY['case-study','finance','invoice-ocr','human-review']::text[],
   true, NULL,
   '{"function":"finance","problem":"The team spends too much time manually triaging invoices and chasing missing fields.","solution":"Use OCR, structured validation, exception routing, and human approval before accounting export.","outcome":"Lower review backlog, clearer audit trail, and fewer unsafe payment actions.","industry":"professional services","company_size":"mid-market"}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000009', NULL, 'regulatory',
   'Human Oversight Starter Note',
   'A plain-language note on why high-impact AI workflows need human review, logging, and clear accountability.',
   ARRAY['m04','m06','m11']::text[], ARRAY['assess','scale']::text[],
   ARRAY['governance','human-oversight','audit','risk']::text[],
   true, NULL,
   '{"jurisdiction":"general","framework":"nist","summary":"For operational AI systems, teams should define the human decision point, logging requirements, escalation paths, and rollback conditions before deployment.","effective_date":"2026-01-01"}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000010', NULL, 'use_case_templates',
   'Invoice OCR and Exception Routing',
   'A starter template for evaluating invoice OCR as an AI use case.',
   ARRAY['m01','m02','m09']::text[], ARRAY['discover','assess']::text[],
   ARRAY['use-case-template','invoice-ocr','finance','scoring']::text[],
   true, NULL,
   '{"industry":"cross-industry","function":"finance","pre_scored_pillars":{"value":4,"data_readiness":3,"risk":3,"workflow_fit":4,"measurability":4,"user_adoption":3,"integration_complexity":3,"governance_readiness":3},"estimated_roi":"medium-high","complexity":"medium"}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000011', NULL, 'glossary',
   'Token',
   'A beginner-friendly definition of tokens in AI systems.',
   ARRAY['m01','m03']::text[], ARRAY['discover']::text[],
   ARRAY['glossary','tokens','ai-basics']::text[],
   true, NULL,
   '{"term":"Token","definition":"A token is a chunk of text that an AI model processes. Tokens can be whole words, parts of words, spaces, or punctuation. Token count affects how much context a model can read and how much a request may cost.","module_first_introduced":"m01","related_terms":["context window","prompt","completion"]}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000012', NULL, 'research',
   'Retrieval-Augmented Generation Overview',
   'A starter research note explaining why retrieval is useful when AI systems need grounded answers from documents.',
   ARRAY['m04','m08']::text[], ARRAY['discover','build']::text[],
   ARRAY['research','rag','knowledge-base','grounding']::text[],
   true, NULL,
   '{"paper_url":"","authors":["House of Ichigo"],"publication_date":"2026-01-01","summary":"Retrieval-augmented generation connects a model to selected source material so answers can be more grounded, current, and auditable.","relevance_to_curriculum":"Supports M04 assistant design and M08 deployment planning."}'::jsonb,
   1),

  ('11111111-0000-4000-8000-000000000013', NULL, 'skills',
   'Prompt Quality Review',
   'A starter skill for reviewing prompts against role, task, context, constraints, examples, and output format.',
   ARRAY['m03','m10']::text[], ARRAY['assess','build']::text[],
   ARRAY['skills','prompting','quality','review']::text[],
   true, NULL,
   '{"skill_type":"prompt-review","methodology_reference":"six-element prompt framework","input_format":"draft prompt text","output_format":"quality checklist with improvement suggestions","version":"1.0"}'::jsonb,
   1)
ON CONFLICT (id) DO UPDATE SET
  type        = EXCLUDED.type,
  title       = EXCLUDED.title,
  summary     = EXCLUDED.summary,
  module_ids  = EXCLUDED.module_ids,
  phase_ids   = EXCLUDED.phase_ids,
  tags        = EXCLUDED.tags,
  published   = EXCLUDED.published,
  content_url = EXCLUDED.content_url,
  metadata    = EXCLUDED.metadata,
  updated_at  = now();
