
ALTER TABLE public.tool_catalog ADD COLUMN IF NOT EXISTS domain text;

-- Backfill from slug for well-known tools; fall back to "<slug>.com" otherwise.
WITH map(slug, domain) AS (VALUES
  ('notion','notion.so'),
  ('slack','slack.com'),
  ('hubspot','hubspot.com'),
  ('salesforce','salesforce.com'),
  ('pipedrive','pipedrive.com'),
  ('intercom','intercom.com'),
  ('zendesk','zendesk.com'),
  ('freshdesk','freshdesk.com'),
  ('jira','atlassian.com'),
  ('confluence','atlassian.com'),
  ('asana','asana.com'),
  ('trello','trello.com'),
  ('linear','linear.app'),
  ('clickup','clickup.com'),
  ('monday','monday.com'),
  ('airtable','airtable.com'),
  ('google-sheets','google.com'),
  ('google-docs','google.com'),
  ('google-drive','google.com'),
  ('google-calendar','google.com'),
  ('gmail','gmail.com'),
  ('google-workspace','workspace.google.com'),
  ('google-analytics','analytics.google.com'),
  ('google-ads','ads.google.com'),
  ('youtube','youtube.com'),
  ('microsoft-365','microsoft.com'),
  ('outlook','outlook.com'),
  ('teams','microsoft.com'),
  ('onedrive','microsoft.com'),
  ('sharepoint','microsoft.com'),
  ('excel','microsoft.com'),
  ('word','microsoft.com'),
  ('powerpoint','microsoft.com'),
  ('power-bi','powerbi.microsoft.com'),
  ('powerbi','powerbi.microsoft.com'),
  ('dropbox','dropbox.com'),
  ('box','box.com'),
  ('zoom','zoom.us'),
  ('webex','webex.com'),
  ('chatgpt','openai.com'),
  ('openai','openai.com'),
  ('anthropic','anthropic.com'),
  ('claude','claude.ai'),
  ('gemini','gemini.google.com'),
  ('mistral','mistral.ai'),
  ('perplexity','perplexity.ai'),
  ('cohere','cohere.com'),
  ('huggingface','huggingface.co'),
  ('stripe','stripe.com'),
  ('paypal','paypal.com'),
  ('square','squareup.com'),
  ('quickbooks','quickbooks.intuit.com'),
  ('xero','xero.com'),
  ('netsuite','netsuite.com'),
  ('sap','sap.com'),
  ('oracle','oracle.com'),
  ('workday','workday.com'),
  ('bamboohr','bamboohr.com'),
  ('gusto','gusto.com'),
  ('rippling','rippling.com'),
  ('greenhouse','greenhouse.io'),
  ('lever','lever.co'),
  ('docusign','docusign.com'),
  ('hellosign','hellosign.com'),
  ('pandadoc','pandadoc.com'),
  ('mailchimp','mailchimp.com'),
  ('sendgrid','sendgrid.com'),
  ('postmark','postmarkapp.com'),
  ('resend','resend.com'),
  ('klaviyo','klaviyo.com'),
  ('marketo','marketo.com'),
  ('pardot','pardot.com'),
  ('zapier','zapier.com'),
  ('make','make.com'),
  ('n8n','n8n.io'),
  ('workato','workato.com'),
  ('tray','tray.io'),
  ('segment','segment.com'),
  ('mixpanel','mixpanel.com'),
  ('amplitude','amplitude.com'),
  ('looker','looker.com'),
  ('tableau','tableau.com'),
  ('metabase','metabase.com'),
  ('snowflake','snowflake.com'),
  ('bigquery','cloud.google.com'),
  ('redshift','aws.amazon.com'),
  ('databricks','databricks.com'),
  ('aws','aws.amazon.com'),
  ('azure','azure.microsoft.com'),
  ('gcp','cloud.google.com'),
  ('cloudflare','cloudflare.com'),
  ('vercel','vercel.com'),
  ('netlify','netlify.com'),
  ('github','github.com'),
  ('gitlab','gitlab.com'),
  ('bitbucket','bitbucket.org'),
  ('figma','figma.com'),
  ('sketch','sketch.com'),
  ('miro','miro.com'),
  ('mural','mural.co'),
  ('canva','canva.com'),
  ('loom','loom.com'),
  ('typeform','typeform.com'),
  ('jotform','jotform.com'),
  ('google-forms','google.com'),
  ('surveymonkey','surveymonkey.com'),
  ('calendly','calendly.com'),
  ('shopify','shopify.com'),
  ('woocommerce','woocommerce.com'),
  ('bigcommerce','bigcommerce.com'),
  ('magento','magento.com'),
  ('wordpress','wordpress.com'),
  ('webflow','webflow.com'),
  ('squarespace','squarespace.com'),
  ('wix','wix.com'),
  ('supabase','supabase.com'),
  ('firebase','firebase.google.com'),
  ('mongodb','mongodb.com'),
  ('postgres','postgresql.org'),
  ('mysql','mysql.com'),
  ('twilio','twilio.com'),
  ('discord','discord.com'),
  ('telegram','telegram.org'),
  ('whatsapp','whatsapp.com'),
  ('linkedin','linkedin.com'),
  ('facebook','facebook.com'),
  ('instagram','instagram.com'),
  ('twitter','twitter.com'),
  ('x','x.com'),
  ('tiktok','tiktok.com'),
  ('reddit','reddit.com'),
  ('pinterest','pinterest.com')
)
UPDATE public.tool_catalog t
SET domain = m.domain
FROM map m
WHERE t.domain IS NULL AND lower(t.slug) = m.slug;

-- Default fallback: derive from slug as <slug>.com (strip suffixes like -api, -app)
UPDATE public.tool_catalog
SET domain = regexp_replace(lower(slug), '[^a-z0-9]+', '', 'g') || '.com'
WHERE domain IS NULL AND slug IS NOT NULL AND slug <> '';
